# Generated by Django 5.0.7 on 2024-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySearchCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('city', 'user')},
            },
        ),
    ]
